services:
  app:
    build: .
    container_name: karbyvisual-dev
    restart: always
    ports:
      # Propojení portu 3001 z kontejneru na Váš počítač (hostitele)
      - "3001:3001"
    env_file:
      - .env
    volumes:
      # Propojení zdrojového kódu pro okamžité promítnutí změn
      - .:/usr/src/app
      # Ochrana node_modules před přepsáním z hostitelského PC (důležité pro Windows vs Linux binary)
      - /usr/src/app/node_modules
      # Propojení databáze pro trvalé ukládání dat přímo na Váš disk
      - ./data:/usr/src/app/data
      # Propojení složky s nahranými obrázky pro trvalé ukládání
      - ./public/uploads:/usr/src/app/public/uploads
